/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EcommerceAdminService } from "../ecommerceAdmin.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EcommerceAdminCreateInput } from "./EcommerceAdminCreateInput";
import { EcommerceAdmin } from "./EcommerceAdmin";
import { EcommerceAdminFindManyArgs } from "./EcommerceAdminFindManyArgs";
import { EcommerceAdminWhereUniqueInput } from "./EcommerceAdminWhereUniqueInput";
import { EcommerceAdminUpdateInput } from "./EcommerceAdminUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EcommerceAdminControllerBase {
  constructor(
    protected readonly service: EcommerceAdminService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EcommerceAdmin })
  @nestAccessControl.UseRoles({
    resource: "EcommerceAdmin",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEcommerceAdmin(
    @common.Body() data: EcommerceAdminCreateInput
  ): Promise<EcommerceAdmin> {
    return await this.service.createEcommerceAdmin({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EcommerceAdmin] })
  @ApiNestedQuery(EcommerceAdminFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EcommerceAdmin",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ecommerceAdmins(
    @common.Req() request: Request
  ): Promise<EcommerceAdmin[]> {
    const args = plainToClass(EcommerceAdminFindManyArgs, request.query);
    return this.service.ecommerceAdmins({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EcommerceAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EcommerceAdmin",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ecommerceAdmin(
    @common.Param() params: EcommerceAdminWhereUniqueInput
  ): Promise<EcommerceAdmin | null> {
    const result = await this.service.ecommerceAdmin({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EcommerceAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EcommerceAdmin",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEcommerceAdmin(
    @common.Param() params: EcommerceAdminWhereUniqueInput,
    @common.Body() data: EcommerceAdminUpdateInput
  ): Promise<EcommerceAdmin | null> {
    try {
      return await this.service.updateEcommerceAdmin({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EcommerceAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EcommerceAdmin",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEcommerceAdmin(
    @common.Param() params: EcommerceAdminWhereUniqueInput
  ): Promise<EcommerceAdmin | null> {
    try {
      return await this.service.deleteEcommerceAdmin({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
